sudo: required
services:
  - docker

before_deploy: 
  - docker build -t nanabarimah/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true nanabarimah/react-test npm test -- --coverage

after_success: 
  - docker build -t nanabappiah7/multi-client ./client
  - docker build -t nanabappiah7/multi-nginx ./nginx
  - docker build -t nanabappiah7/multi-server ./server
  - docker build -t nanabappiah7/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push nanabappiah7/multi-client
  - docker push nanabappiah7/multi-nginx
  - docker push nanabappiah7/multi-server
  - docker push nanabappiah7/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'ap-southeast-2'
  app: 'multi-docker'
  env: 'Multi-docker-env'
  bucket_name: 'elasticbeanstalk-ap-southeast-2-851725170596'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY